name: barrel_trader
description: "BARREL - Paper-trade crude oil & natural gas markets in real time."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  provider: ^6.1.2
  intl: ^0.19.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
