name: aura_meter
description: "AURA METER - Scan your aura. Farm your vibe. Beat your friends."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  share_plus: ^9.0.0
  provider: ^6.1.2
  vibration: ^2.0.0
  confetti: ^0.7.0
  google_mobile_ads: ^5.1.0
  path_provider: ^2.1.4
  in_app_review: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/aura_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#07060F"
  adaptive_icon_background: "#07060F"
  adaptive_icon_foreground: "assets/icon/aura_icon_fg.png"
  web:
    generate: true
    image_path: "assets/icon/aura_icon.png"
    background_color: "#07060F"
    theme_color: "#9D5CFF"

flutter_native_splash:
  color: "#07060F"
  image: "assets/icon/aura_icon_fg.png"
  android_12:
    color: "#07060F"
    image: "assets/icon/aura_icon_fg.png"
  ios: true
  android: true
  web: false
